### ISSUE TITLE
Getting Internal Server errors now, Error 500 when trying to book, thanks!

### ISSUE THREAD

**Issue by eastatlantasanta** [lgrees/resy-cli#3]

**Comment by lgrees** [comment]
@eastatlantasanta sorry just seeing this - I was able to reproduce. Seeing the following in the logs:

```
{"level":"warn","error":"failed to book reservation, status code: 500","slot":{"reservation_time":"2023-06-09 18:30:00","reservation_type":"Indoor"},"time":"2023-06-01T08:48:07-04:00","message":"booking slot failed"}
```

Must be something new that `resy` is doing to restrict this. If I get some time I'll take a look.

**Comment by lstephanian** [comment]
same, I've been pinging their API separately and I get a similar error. curious if you've found anything out on this.

**Comment by OpentheChampagne** [comment]
@lgrees @lstephanian Not sure if you've seen this thread. https://github.com/Alkaar/resy-booking-bot/issues/120

Might be something they're doing with the user-agent.

**Comment by lstephanian** [comment]
got it working, ty @f-eli-pe !

**Comment by lgrees** [comment]
Cool - thanks @f-eli-pe ! I finally have time this long weekend to fix. Who knew this project actually had users! 😄

**Comment by lgrees** [comment]
Just verified that this is fixed in the new release - thanks @eastatlantasanta for flagging!

**Comment by sethtrei** [comment]
Hey, I think this issue should be re-opened. I am getting the same issue as OP. Some logs:

{"level":"info","matching_slots":[{"reservation_time":"2023-09-07 20:30:00","reservation_type":"Dining"},{"reservation_time":"2023-09-07 20:30:00","reservation_type":"Patio"}],"time":"2023-08-14T14:27:39-04:00","message":"found matching slots"}
{"level":"info","slot":{"reservation_time":"2023-09-07 20:30:00","reservation_type":"Dining"},"time":"2023-08-14T14:27:39-04:00","message":"attempting to book slot"}
{"level":"warn","error":"failed to book reservation, status code: 500","slot":{"reservation_time":"2023-09-07 20:30:00","reservation_type":"Dining"},"time":"2023-08-14T14:27:39-04:00","message":"booking slot failed"}

It's worth noting that this reservation is clearly available on resy.com. The restaurant has full availability for the day I'm trying to book via the CLI.

**Comment by lgrees** [comment]
Hey - sorry for the delay. I unfortunately won't be able to look into this for a bit. The nature of this project is such that it will always be lagging whenever resy decides they want to make changes to their API.

I'm unable to reproduce myself (I just booked using the CLI). @sethtrei , can you confirm that you're running the latest version of the CLI by running:

```
resy -v // should return 'resy version 0.4.0'
```

**Comment by sethtrei** [comment]
Hi! No worries. It's actually working now. No idea what changed between now and when I last tried.... will comment again if it breaks in the future. Thanks so much!

**Comment by zrabin** [comment]
@lgrees FWIW, this issue seems to have reappeared

```
 ~ >> resy book --partySize=2 --reservationDate=2024-02-18 --reservationTimes=20:00:00 --venueId=2038
Error: failed to fetch slots for date, status code: 500
```

**Comment by lgrees** [comment]
Huh @zrabin I'm able to repro. I added some additional logging locally and `Internal Server Error` is the only context they give. Seems like it's blowing up at a different step in the booking process vs. before. I'll try to see if I can fix. Hopefully not too bad. Thanks for flagging!

**Comment by lgrees** [comment]
Okay this should be fixed with the latest release (worked for me - let me know). Out of curiosity, are you using the direct `resy book` more than `resy schedule`? 

`resy schedule` is maybe a little finicky with `at`, wondering if it would be helpful to make `schedule` simply sleep until booking time. I originally didn't do this because I wanted something more "set it and forget it". But maybe worth adding this option.

**Comment by zrabin** [comment]
I just tested `resy book` again, and it worked, so thanks for the fix. I'm much more interested in using the `resy schedule` feature. I'm going to try that tonight for a reservation that will be made available at 9am ET tomorrow morning.

**Comment by zrabin** [comment]
@lgrees When entering reservation times using the `resy schedule` feature, are they in military time? For example, if I want to try for a 6:00pm table, do I enter it as 06:00 or 18:00?

**Comment by lgrees** [comment]
Hey @zrabin it's military time

**Comment by jakeg0615** [comment]
Hey @lgrees, looks like the issue may have reappeared again with the Internal Server Error, both for `resy book` and `resy schedule`, for restaurants that have ostensibly open slots:

`Error: failed to fetch slots for date, status code: 500`.

Not sure if you're able to reproduce. On the most recent version as well (`resy 0.6.0`).
