### ISSUE TITLE
Venue reply invalid

### ISSUE THREAD

**Issue by mrlnyc** [lgrees/resy-cli#8]
Hi, I could be dumb but its not letting me enter my own venueId for schedule. Every time I try to enter the venueId number the bot gives me a "Sorry, your reply was invalid: please tab to search and select a venue" When I tab it only gives me a select few restaurants. I was able to book an immediate reservation, just could not use the schedule feature.

**Comment by fanniva** [comment]
I am having the same issue, function is set to print out 5 options. No option to print out more options and cannot specify venueID which would be needed...

**Comment by lgrees** [comment]
The user interface is a little wonky here. I originally had users just enter the `venueID` number directly. But I thought it would be nicer to allow users to search for restaurants similar to the resy UI (don't have to leave the CLI to schedule the booking). 

This input now wants you to enter a search string which you can autocomplete by tabbing (see video below).

This is a bit of a hack/workaround to support search with the prompt library that I'm using. Hopefully this answers your question - please feel free to reopen if not.

https://github.com/lgrees/resy-cli/assets/10553910/803d73ee-7df5-47be-986b-ebf8548e92df
